apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-sim
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fitzss/fleet-sim
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
      - values-gitops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: robot-fleet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
