{{- if not .Values.monitor.useRollout }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-monitor
  template:
    metadata:
      labels:
        app: fleet-monitor
    spec:
      containers:
      - name: monitor
        image: {{ .Values.monitor.image }}
        imagePullPolicy: {{ .Values.monitor.imagePullPolicy }}
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
{{- end }}
